sudo: required
services:
  - docker

script:
  - docker build -t jasonrey/code-server-with-docker .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jasonrey/code-server-with-docker
